name: flutter_form_builder
description: A Flutter application for building and managing forms with real-time persistence.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # State Management
  flutter_bloc: ^9.1.0
  hydrated_bloc: ^10.0.0
  # Navigation
  auto_route: ^10.0.1
  # UI/Layout
  gap: ^3.0.1
  # Models & Code Generation
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  # Utilities
  uuid: ^4.3.3
  path_provider: ^2.1.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  freezed: ^3.0.4
  json_serializable: ^6.7.1
  auto_route_generator: ^10.0.1
  bloc_test: ^10.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
